// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using GitHubJobs.Core.Data.Models.Incoming;
using UIKit;

namespace GitHubJobs.iOS.Tables.Cells
{
	public partial class JobCell : UITableViewCell
	{
		public JobCell (IntPtr handle) : base (handle)
		{
		}

        public JobCell(UITableViewCellStyle style, string reuseIdentifier)
            : base(style, reuseIdentifier)
        {
        }

        public void UpdateCell(JobDescription job)
        {
            this.JobDesription.Text = job.Description;
            this.JobTitle.Text = job.Title;
            this.JobCompany.Text = job.Company;
            this.JobType.Text = job.Type;
            this.JobLocation.Text = job.Location;
        }
	}
}
